on:
  push:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set
        run: |
          files=$(find packages -type f -name "opam" -exec dirname {} \;)
          json=$(printf '%s' "$files" | jq -R . | jq -s '{include: map({ bin: .})}')
          {
            echo "matrix<<EOF"
            echo "$json"
            echo "EOF"
          } >> $GITHUB_OUTPUT

  install-library-from-opam-repo:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: setting up opam
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0
      - name: install dependencies from opam
        run: |
          opam repository -a --set-default add lambdapi https://github.com/deducteam/opam-lambdapi-repository.git

      - name: install library ${{ matrix.bin }} 
        run: |
          echo "installing ${{ matrix.bin }}"
          opam install -y --deps-only "${{ matrix.bin }}"

  install-library-from-master:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: setting up opam
        uses: ocaml/setup-ocaml@v3
        with:
        # It would be nice to compute the latest version of ocaml that is supported by ${{ matrix.lib }} 
        # A first approximation could be to use version 5.3.0 if there is ANY upper bound constraint on the library. Lastest if none.
        # Problem : the lib could support a more recent version. 

        # Another option would be to use a script that dry runs opam install the lib with different versions of ocaml and pick the latest version that is supported :
        #   for v in $(VERSIONS); do \
  #           if opam install $$lib ocaml-base-compiler.$$v --dry-run >/dev/null 2>&1; then \
  #             echo "{\"lib\":\"$$lib\",\"version\":\"$$v\"}" >> $$tmp; \
  #           fi; \
  #          done; \
          ocaml-compiler: 5.3.0
      - name: check compatibility with LP master version
        id: check
        # This should probably moved to a different workflow !!!
        # To pick the right version of Lambdapi (master or another version)
        # We first test whether the package has a upper bound constraint on some Lambdapi dependency (whether Lambdapi or just another LP library. We assume other dependencies do not impact LP version).
        # If this is the case, this means the lib will (proobably) not work with the latest (master) version 
        # of Lambdapi (whether the constraints is related to Lambdapi directly or indirecttly)
        # So, the right version of Lambdapi is installed from the Opam repository (In the future, this should probably be the unique way to install Lambdapi
        # and the above should be moved to a dedicated workflow)

        # For the "internal" dependencies (meaning other LP libraries in the current repo) installation is always made from the local repo with Opam managing versions
        run: |
          if ! grep -q "lambdapi.*<=" ${{ matrix.bin }}/opam; then
            echo "compatibleWithLambdapiMaster=true" >> $GITHUB_OUTPUT
          fi
      - name: install Lambdapi from master
      # If compatibleWithLambdapiMaster then install from LP github repo. Otherwise, clone and install from Opam repo
        if: steps.check.outputs.compatibleWithLambdapiMaster == 'true'
        run: |
          git clone https://github.com/Deducteam/lambdapi.git
          cd lambdapi
          opam install --deps-only .
          eval $(opam env)
          opam install -y .
          cd ..
      - name: install dependencies from master
        run: |
          opam repository -a --set-default add lambdapi .
      - name: install library ${{ matrix.bin }} 
        run: |
          echo "installing ${{ matrix.bin }}"
          opam install -y --deps-only "${{ matrix.bin }}"
