name: test packages

on:
  push

jobs:
  get-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        # with:
        #   files: |
        #     packages/**/opam
      - name: Display changed files
        run: |
          )
          echo "Fichiers modifiés :"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do   
            echo "$file"
          done
          
          modifiedPkgs=$(
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            pkg=$(basename "$(dirname "$(dirname $file)")")
            echo $pkg
          done

          for file in $modifiedPkgs; do
            echo  pkg $file has been modified
          done
